### ISSUE TITLE
Print com ("""  """)

### ISSUE THREAD

**Issue by victorvp9** [Maurrici/Apple-Developer-Academy#2]
Acredito que o "print" desse menu poderia ter sido feito utilizando as 3 ", melhoraria a legibilidade e compreensão:
```swift
print("""
// Forma do print desejado
""")
``` 

https://github.com/Maurrici/Challenges/blob/b0bb3b4c46553fe7428d03515ffdc5383be1941d/PasswordCloud/PasswordCloud/main.swift#LL135C9-L135C9

**Comment by Maurrici** [comment]
Resolvido meu patrão!

<img width="818" alt="image" src="https://github.com/Maurrici/Challenges/assets/53577592/bbccd72e-783a-46a5-8b21-dedf80cfd810">
