### ISSUE TITLE
Opções de procura da senha

### ISSUE THREAD

**Issue by victorvp9** [Maurrici/Apple-Developer-Academy#3]
Poderia implementar também uma forma de procurar por outro campo que não seja somente o URL
https://github.com/Maurrici/Challenges/blob/b0bb3b4c46553fe7428d03515ffdc5383be1941d/PasswordCloud/PasswordCloud/main.swift#LL126C6-L126C6

**Comment by Maurrici** [comment]
Entendi, porém desnecessário.
