### ISSUE TITLE
Confusão sobre a opção de especificar URLs

### ISSUE THREAD

**Issue by tiago-vargas** [Maurrici/Apple-Developer-Academy#6]
Eu achei confuso pedir URLs na hora de salvar uma senha. O app continua salvando as senhas em `data.json` na minha pasta de documentos, e não na URL que eu passei. Talvez pedir uma descrição (pra eu poder me lembrar sobre o que é a senha) ao invés da URL seria melhor.

**Comment by rodscesars** [comment]
Obrigado, resolvido!
