### ISSUE TITLE
Criação da senha

### ISSUE THREAD

**Issue by victorvp9** [Maurrici/Apple-Developer-Academy#8]
Quando definida manualmente, o algoritmo deixa criar uma senha com menos de 5 dígitos, mas automaticamente, ele exige no mínimo 5 dígitos da senha. Não permite que o usuário crie uma senha vazia, perfeito, porém o usuário consegue criar uma senha, usuário e url apertando espaço e depois confirmando.

**Comment by rodscesars** [comment]
Grato, Victor!
Problema resolvido.
